//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTZ_Transports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbAbastecimentos
    {
        public int id { get; set; }
        public int idVeiculo { get; set; }
        public int idMotorista { get; set; }
        public System.DateTime abastecimentoDate { get; set; }
        public int idCombustivel { get; set; }
        public double quantidade { get; set; }
        public string observacoes { get; set; }
        public System.DateTime createDate { get; set; }
        public System.DateTime updateDate { get; set; }
        public double Total { get; set; }
    
        public virtual TbTipoCombustivel TbTipoCombustivel { get; set; }
        public virtual TbMotorista TbMotorista { get; set; }
        public virtual TbCarro TbCarro { get; set; }
    }
}
